;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
+GameplayTagRedirects=(OldTagName="Event.DayChange",NewTagName="Event.DayChanged")
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Event.DayChanged",DevComment="")
+GameplayTagList=(Tag="Event.Hit.Enemy",DevComment="")
+GameplayTagList=(Tag="Event.HPChanged",DevComment="")
+GameplayTagList=(Tag="Event.HungerChanged",DevComment="")
+GameplayTagList=(Tag="Event.StaminaChanged",DevComment="")
+GameplayTagList=(Tag="Event.Weapon.ZoomIn",DevComment="")
+GameplayTagList=(Tag="Event.Weapon.ZoomOut",DevComment="")
+GameplayTagList=(Tag="HUD.Slot.Compass",DevComment="")
+GameplayTagList=(Tag="HUD.Slot.Day",DevComment="")
+GameplayTagList=(Tag="HUD.Slot.InteractionText",DevComment="")
+GameplayTagList=(Tag="HUD.Slot.PlayerState",DevComment="")
+GameplayTagList=(Tag="HUD.Slot.QuickBar",DevComment="")
+GameplayTagList=(Tag="HUD.Slot.Recticle",DevComment="")
+GameplayTagList=(Tag="HUD.Slot.Stamina",DevComment="")
+GameplayTagList=(Tag="HUD.Slot.WeaponState",DevComment="")
+GameplayTagList=(Tag="HUD.Slot.WorldState",DevComment="")
+GameplayTagList=(Tag="UI.Action.LeftClick",DevComment="")
+GameplayTagList=(Tag="UI.Action.Preview.LeftClick",DevComment="")
+GameplayTagList=(Tag="UI.Action.RightClick",DevComment="")
+GameplayTagList=(Tag="UI.Action.WheelDown",DevComment="")
+GameplayTagList=(Tag="UI.Action.WheelUp",DevComment="")
+GameplayTagList=(Tag="UI.Layer.Game",DevComment="")
+GameplayTagList=(Tag="UI.Layer.GameMenu",DevComment="")
+GameplayTagList=(Tag="UI.Layer.Menu",DevComment="")
+GameplayTagList=(Tag="UI.Layer.Modal",DevComment="")

